from __future__ import annotations

from enum import Enum


READ_MODEL_SCHEMA_VERSION = "RL_P2_READ_MODEL_V0_1R1"
LOGICAL_HASH_REGISTRY_VERSION = "RL_P2_LOGICAL_HASH_REGISTRY_V0_1R1"
BUILDER_CONTRACT_VERSION = "RL_P2_BUILDER_CONTRACT_V0_1R1"
TOKENIZER_CONTRACT_VERSION = "RL_P2_UNICODE61_CJK_BIGRAM_V0_1"
POINTER_SCHEMA_VERSION = "RL_P2_CURRENT_POINTER_V0_1R1"
BUILD_MODE = "FULL_VALIDATED_REBUILD"


class GenerationState(str, Enum):
    VALID_CURRENT_GENERATION = "VALID_CURRENT_GENERATION"
    STALE_GENERATION = "STALE_GENERATION"
    INCOMPATIBLE_GENERATION = "INCOMPATIBLE_GENERATION"
    CORRUPT_OR_TAMPERED_GENERATION = "CORRUPT_OR_TAMPERED_GENERATION"
    INCOMPLETE_BUILD = "INCOMPLETE_BUILD"
    AMBIGUOUS = "AMBIGUOUS"


class SearchScope(str, Enum):
    CURRENT = "CURRENT"
    HISTORY = "HISTORY"
