from __future__ import annotations

from enum import Enum


EVENT_SCHEMA_VERSION = "RL_EVENT_V0_2"
LEDGER_SCHEMA_VERSION = "RL_LEDGER_V0_2"
PROJECTION_SCHEMA_VERSION = "RL_PROJECTION_V0_2"
CHECKPOINT_SCHEMA_VERSION = "RL_CHECKPOINT_V0_2"
EVENT_REGISTRY_VERSION = "RL_EVENT_REGISTRY_V0_2"
PROJECT_ID = "AI_VIDEO_PIPELINE_REFERENCE_LIBRARY"


class AuthorityClass(str, Enum):
    OBSERVATION_ONLY = "OBSERVATION_ONLY"
    MODEL_PROPOSAL = "MODEL_PROPOSAL"
    HUMAN_DECISION = "HUMAN_DECISION"
    EXTERNAL_EXECUTION_RECEIPT = "EXTERNAL_EXECUTION_RECEIPT"


class AggregateType(str, Enum):
    PAIR = "PAIR"
    CLUSTER = "CLUSTER"
    REPRESENTATIVE_WORKFLOW = "REPRESENTATIVE_WORKFLOW"


class EventType(str, Enum):
    DUPLICATE_EVIDENCE_ADDED = "DUPLICATE_EVIDENCE_ADDED"
    DUPLICATE_EVIDENCE_RETRACTED = "DUPLICATE_EVIDENCE_RETRACTED"
    PAIR_RELATION_PROPOSAL_ADDED = "PAIR_RELATION_PROPOSAL_ADDED"
    PAIR_RELATION_DECISION_RECORDED = "PAIR_RELATION_DECISION_RECORDED"
    CLUSTER_PROPOSAL_ADDED = "CLUSTER_PROPOSAL_ADDED"
    CLUSTER_CONFIRMATION_RECORDED = "CLUSTER_CONFIRMATION_RECORDED"
    CLUSTER_CONFIRMATION_RETRACTED = "CLUSTER_CONFIRMATION_RETRACTED"
    REPRESENTATIVE_PROPOSAL_ADDED = "REPRESENTATIVE_PROPOSAL_ADDED"
    REPRESENTATIVE_PROPOSAL_SUPERSEDED = "REPRESENTATIVE_PROPOSAL_SUPERSEDED"
    REPRESENTATIVE_PROPOSAL_RETRACTED = "REPRESENTATIVE_PROPOSAL_RETRACTED"
    REPRESENTATIVE_DECISION_RECORDED = "REPRESENTATIVE_DECISION_RECORDED"
    WORKFLOW_EXECUTION_AUDIT_RECORDED = "WORKFLOW_EXECUTION_AUDIT_RECORDED"
