from __future__ import annotations

from enum import Enum


EVENT_SCHEMA_VERSION = "RL_EVENT_V0_1"
LEDGER_SCHEMA_VERSION = "RL_LEDGER_V0_1"
PROJECTION_SCHEMA_VERSION = "RL_PROJECTION_V0_1"
CHECKPOINT_SCHEMA_VERSION = "RL_CHECKPOINT_V0_1"
EVENT_REGISTRY_VERSION = "RL_EVENT_REGISTRY_V0_1"
PROJECT_ID = "AI_VIDEO_PIPELINE_REFERENCE_LIBRARY"


class AuthorityClass(str, Enum):
    OBSERVATION_ONLY = "OBSERVATION_ONLY"
    MODEL_PROPOSAL = "MODEL_PROPOSAL"
    HUMAN_DECISION = "HUMAN_DECISION"
    EXTERNAL_EXECUTION_RECEIPT = "EXTERNAL_EXECUTION_RECEIPT"
    SYSTEM_PROJECTION = "SYSTEM_PROJECTION"


class EventType(str, Enum):
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    EXECUTION_AUDIT_RECORDED = "EXECUTION_AUDIT_RECORDED"
    HUMAN_DECISION_RECORDED = "HUMAN_DECISION_RECORDED"
    RELATIONSHIP_ASSERTION_ADDED = "RELATIONSHIP_ASSERTION_ADDED"
    RELATIONSHIP_ASSERTION_RETRACTED = "RELATIONSHIP_ASSERTION_RETRACTED"
    REVIEW_OBSERVATION_ADDED = "REVIEW_OBSERVATION_ADDED"
    REVIEW_OBSERVATION_CORRECTED = "REVIEW_OBSERVATION_CORRECTED"
    RIGHTS_DECISION_RECORDED = "RIGHTS_DECISION_RECORDED"
    RIGHTS_EVIDENCE_ADDED = "RIGHTS_EVIDENCE_ADDED"
    SCORE_RECORD_ADDED = "SCORE_RECORD_ADDED"
    SCORE_RECORD_SUPERSEDED = "SCORE_RECORD_SUPERSEDED"
    STORAGE_PROPOSAL_ADDED = "STORAGE_PROPOSAL_ADDED"
    STORAGE_PROPOSAL_SUPERSEDED = "STORAGE_PROPOSAL_SUPERSEDED"
    TAXONOMY_SNAPSHOT_BOUND = "TAXONOMY_SNAPSHOT_BOUND"
