from __future__ import annotations

from enum import Enum


READ_MODEL_SCHEMA_VERSION = "RL_P3_READ_MODEL_SCHEMA_V0_1"
LOGICAL_HASH_REGISTRY_VERSION = "RL_P3_LOGICAL_HASH_REGISTRY_V0_1"
POINTER_SCHEMA_VERSION = "RL_P3_POINTER_SCHEMA_V0_1"
BUILDER_CONTRACT_VERSION = "RL_P3_BUILDER_CONTRACT_V0_1"
BUILD_MODE = "FULL_VALIDATED_REBUILD"


class GenerationState(str, Enum):
    VALID_CURRENT_GENERATION = "VALID_CURRENT_GENERATION"
    STALE_GENERATION = "STALE_GENERATION"
    INCOMPATIBLE_GENERATION = "INCOMPATIBLE_GENERATION"
    CORRUPT_OR_TAMPERED_GENERATION = "CORRUPT_OR_TAMPERED_GENERATION"
    INCOMPLETE_BUILD = "INCOMPLETE_BUILD"
    AMBIGUOUS = "AMBIGUOUS"
